# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RcppDisc <- function(vec, n = 5L, method = "natural", sample_begin = 3000L, sample_prop = 0.15, seed = 123456789L, threshold = 0.4, iter_step = 100L, breakpoints = NULL, right_closed = TRUE) {
    .Call(`_infoxtr_RcppDisc`, vec, n, method, sample_begin, sample_prop, seed, threshold, iter_step, breakpoints, right_closed)
}

RcppDist4Vec <- function(v1, v2, method = "euclidean", na_rm = TRUE, na_comp = TRUE) {
    .Call(`_infoxtr_RcppDist4Vec`, v1, v2, method, na_rm, na_comp)
}

RcppDist4Mat <- function(mat, method = "euclidean", na_rm = TRUE, na_comp = TRUE, byrow = TRUE) {
    .Call(`_infoxtr_RcppDist4Mat`, mat, method, na_rm, na_comp, byrow)
}

RcppDist4MatSub <- function(mat, lib, pred, method = "euclidean", na_rm = TRUE, na_comp = TRUE, byrow = TRUE) {
    .Call(`_infoxtr_RcppDist4MatSub`, mat, lib, pred, method, na_rm, na_comp, byrow)
}

RcppInfoImbalance <- function(Mx, My, lib, pred, k = 3L, threads = 1L, method = "euclidean", na_comp = TRUE) {
    .Call(`_infoxtr_RcppInfoImbalance`, Mx, My, lib, pred, k, threads, method, na_comp)
}

RcppImbalanceGain <- function(Mx, My, alpha, lib, pred, h = 1L, k = 3L, threads = 1L, method = "euclidean", na_comp = TRUE) {
    .Call(`_infoxtr_RcppImbalanceGain`, Mx, My, alpha, lib, pred, h, k, threads, method, na_comp)
}

RcppImbalanceGainCausality <- function(mat, target, agent, alpha, lib, pred, E = as.integer( c(3)), tau = as.integer( c(1)), style = 1L, h = 0L, k = 3L, threads = 1L, method = "euclidean", na_comp = TRUE, nb = NULL, nrows = NULL) {
    .Call(`_infoxtr_RcppImbalanceGainCausality`, mat, target, agent, alpha, lib, pred, E, tau, style, h, k, threads, method, na_comp, nb, nrows)
}

RcppDiscEntropy <- function(series, base = 2.0, na_rm = TRUE) {
    .Call(`_infoxtr_RcppDiscEntropy`, series, base, na_rm)
}

RcppContEntropy <- function(vec, k = 3L, alg = 0L, base = 2.0) {
    .Call(`_infoxtr_RcppContEntropy`, vec, k, alg, base)
}

RcppDiscJE <- function(mat, vars, base = 2.0, na_rm = TRUE) {
    .Call(`_infoxtr_RcppDiscJE`, mat, vars, base, na_rm)
}

RcppContJE <- function(mat, vars, k = 3L, alg = 0L, base = 2.0, na_comp = TRUE) {
    .Call(`_infoxtr_RcppContJE`, mat, vars, k, alg, base, na_comp)
}

RcppDiscCE <- function(mat, target, conds, base = 2.0, na_rm = TRUE) {
    .Call(`_infoxtr_RcppDiscCE`, mat, target, conds, base, na_rm)
}

RcppContCE <- function(mat, target, conds, k = 3L, alg = 0L, base = 2.0, na_comp = TRUE) {
    .Call(`_infoxtr_RcppContCE`, mat, target, conds, k, alg, base, na_comp)
}

RcppDiscMI <- function(mat, target, interact, base = 2.0, na_rm = TRUE, normalize = FALSE) {
    .Call(`_infoxtr_RcppDiscMI`, mat, target, interact, base, na_rm, normalize)
}

RcppContMI <- function(mat, target, interact, k = 3L, alg = 0L, base = 2.0, na_comp = TRUE, normalize = FALSE) {
    .Call(`_infoxtr_RcppContMI`, mat, target, interact, k, alg, base, na_comp, normalize)
}

RcppDiscCMI <- function(mat, target, interact, conds, base = 2.0, na_rm = TRUE, normalize = FALSE) {
    .Call(`_infoxtr_RcppDiscCMI`, mat, target, interact, conds, base, na_rm, normalize)
}

RcppContCMI <- function(mat, target, interact, conds, k = 3L, alg = 0L, base = 2.0, na_comp = TRUE, normalize = FALSE) {
    .Call(`_infoxtr_RcppContCMI`, mat, target, interact, conds, k, alg, base, na_comp, normalize)
}

RcppDiscTE <- function(mat, target, agent, lag_p = 3L, lag_q = 3L, base = 2.0, na_rm = TRUE, normalize = FALSE, lag_single = FALSE) {
    .Call(`_infoxtr_RcppDiscTE`, mat, target, agent, lag_p, lag_q, base, na_rm, normalize, lag_single)
}

RcppContTE <- function(mat, target, agent, lag_p = 3L, lag_q = 3L, k = 3L, alg = 0L, base = 2.0, na_comp = TRUE, normalize = FALSE, lag_single = FALSE) {
    .Call(`_infoxtr_RcppContTE`, mat, target, agent, lag_p, lag_q, k, alg, base, na_comp, normalize, lag_single)
}

RcppDiscSURD <- function(mat, max_order = 3L, threads = 1L, base = 2.0, normalize = TRUE) {
    .Call(`_infoxtr_RcppDiscSURD`, mat, max_order, threads, base, normalize)
}

RcppKOCMI <- function(mat, target, agent, conds, knockoff, null_knockoff = NULL, type = "cont", nboots = 10000L, k = 3L, alg = 0L, threads = 1L, seed = 123456789L, base = 2.0, method = "equal", contain_null = TRUE, na_comp = TRUE) {
    .Call(`_infoxtr_RcppKOCMI`, mat, target, agent, conds, knockoff, null_knockoff, type, nboots, k, alg, threads, seed, base, method, contain_null, na_comp)
}

RcppGenLatticeLag <- function(mat, nb, lag = 1L) {
    .Call(`_infoxtr_RcppGenLatticeLag`, mat, nb, lag)
}

RcppGenGridLag <- function(mat, nrows, lag = 1L) {
    .Call(`_infoxtr_RcppGenGridLag`, mat, nrows, lag)
}

RcppGenTSLag <- function(mat, lag = 1L) {
    .Call(`_infoxtr_RcppGenTSLag`, mat, lag)
}

RcppNN4Mat <- function(mat, k, method = "euclidean", include_self = FALSE, na_comp = TRUE, byrow = TRUE) {
    .Call(`_infoxtr_RcppNN4Mat`, mat, k, method, include_self, na_comp, byrow)
}

RcppNN4MatSub <- function(mat, lib, pred, k, method = "euclidean", include_self = FALSE, na_comp = TRUE, byrow = TRUE) {
    .Call(`_infoxtr_RcppNN4MatSub`, mat, lib, pred, k, method, include_self, na_comp, byrow)
}

RcppNN4DistMat <- function(distmat, k, include_self = FALSE) {
    .Call(`_infoxtr_RcppNN4DistMat`, distmat, k, include_self)
}

RcppNN4DistMatSub <- function(distmat, lib, pred, k, include_self = FALSE) {
    .Call(`_infoxtr_RcppNN4DistMatSub`, distmat, lib, pred, k, include_self)
}

RcppSURD <- function(mat, target, agent, lag = 1L, max_order = 3L, threads = 1L, base = 2.0, normalize = TRUE, bin = as.integer( c(5)), method = as.character( c("equal")), nb = NULL, nrows = NULL) {
    .Call(`_infoxtr_RcppSURD`, mat, target, agent, lag, max_order, threads, base, normalize, bin, method, nb, nrows)
}

